### ISSUE TITLE
data not getting written

### ISSUE THREAD

**Issue by nsauro** [PeterGrace/opentsdb-docker#18]
Hi,

I'm able to get this all up and running, but when I try to write data to it, I see it appear in the TSDB autocomplete fields, but I constantly get "No data found", even though when I write, i'm getting no error messages.

I bind mounted in a directory on my host system to see what is getting written to the `/data/hbase`, and I do indeed see the tables and such, but there is no data in them.

What am I doing wrong?

**Comment by soeren-lubitz** [comment]
are you sure that your timestamps are correct?
check https://github.com/soeren-lubitz/csv-to-opentsdb for the complete working setup example

**Comment by PeterGrace** [comment]
Hi, I'm closing this issue since I don't think it was due to the container that the data was not being recorded.  That being said, if you still think this issue is due to the container, I'd ask you try the latest container I'll be uploading today to see if the issue persists.  Feel free to reopen the issue at that point.  Thanks for trying the image and sorry for the long time that I haven't responded!
