### ISSUE TITLE
How to change OpenTSDB server port

### ISSUE THREAD

**Issue by ShanQincheng** [PeterGrace/opentsdb-docker#35]
Hi PeterGrace:

I want to change openTsdb default port number from 4242 to 4949.  I change the port configuration number in all files which located in files directory (include Dockerfile), then I build a new IMAGE from Dockerfile.

I start a container from the new IMAGE, container runs well but openTsdb doesn't work, I can't connect to the ip:4949.

Can you tell me how to change the OpenTSDB default port?

Thanks

**Comment by PeterGrace** [comment]
Hello @ShanQincheng, did you change the opentsdb.conf line with the port?  https://github.com/PeterGrace/opentsdb-docker/blob/a335bf08e0d5a1e8674b3eed91b4e59613d8b340/files/opentsdb.conf#L1  

If you changed that, rebuilt the container after that change, and it still was on 4242 instead of 4949, that might indicate that the opentsdb.conf file isn't being properly read.

**Comment by ShanQincheng** [comment]
Yes, I did. But it didn't work for me. I even change all the port number in all files which located in the file directory, and then rebuild the image from the Dockerfile.

I think use the default port may be unsafe, that's why I insist change the port...
